## Problem 2

In [1]:
import numpy as np
import scipy.stats as sts
import matplotlib.pyplot as plt
import scipy.optimize as opt

In [2]:
data=np.loadtxt('/Users/rubyzhang/Desktop/UChicago/OSML/BootCamp2017/Econ/Wk4_StrEst/data/MacroSeries.txt',delimiter=',')
ct = data[:,0]
kt = data[:,1]
wt = data[:,2]
rt = data[:,3]
beta = 0.99

## a)

In [3]:
# Define the pdf function for macro series:
def pdf_macro(wt,kt,alpha,rho,mu,sigma):
    zt = np.log(wt/((1-alpha)*(kt**alpha))) # Finding zt using equation 3
    pdf_vals = np.empty_like(zt)
    for i in range(len(zt)):
        if i==0:
            miu = mu
        else:
            miu = rho*zt[i-1]+(1-rho)*mu
        pdf_vals[i] = (1/(sigma * np.sqrt(2 * np.pi)) *
                    np.exp( - (zt[i] - miu)**2 / (2 * sigma**2)))
    pdf_vals[pdf_vals==0] = 1e-15
    return pdf_vals

# Define log likelihood function for the Macro Series 
def log_lik_macro(wt,kt,alpha,rho,mu,sigma):
    pdf_vals = pdf_macro(wt,kt,alpha,rho,mu,sigma)
    ln_pdf_vals = np.log(pdf_vals)
    log_lik_val = ln_pdf_vals.sum()
    return log_lik_val

def crit(params, *args):
    alpha,rho,mu,sigma = params
    wt,kt = args
    log_lik_val = log_lik_macro(wt,kt,alpha,rho,mu,sigma)
    neg_log_lik_val = -log_lik_val
    return neg_log_lik_val

alpha_init = 0.5
rho_init = 0.7
mu_init = 9.5
sigma_init = 0.1
params_init = np.array([alpha_init, rho_init, mu_init, sigma_init])
args = (wt,kt)
bounds = ((1e-10,1),(-1,1),(1e-10,None),(1e-10,None))
results = opt.minimize(crit, params_init, args=args, bounds=bounds)
alpha_MLE, rho_MLE, mu_MLE, sigma_MLE = results.x
print(results)
print('alpha_MLE=', alpha_MLE, 'rho_MLE=', rho_MLE, 'mu_MLE=', mu_MLE, 'sigma_MLE', sigma_MLE)
print('MLE log-likelihood: ', log_lik_macro(wt,kt,alpha_MLE, rho_MLE, mu_MLE, sigma_MLE))
print('Inverse Hessian:\n', results.hess_inv.todense())

      fun: -96.706876735303524
 hess_inv: <4x4 LbfgsInvHessProduct with dtype=float64>
      jac: array([  1.35571554e-03,  -8.66862138e-05,  -2.48121523e-03,
        -5.17275112e-04])
  message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
     nfev: 140
      nit: 17
   status: 0
  success: True
        x: array([ 0.45933471,  0.71916622,  9.49729783,  0.09199624])
alpha_MLE= 0.459334708116 rho_MLE= 0.719166224431 mu_MLE= 9.49729783388 sigma_MLE 0.091996238134
MLE log-likelihood:  96.7068767353
Inverse Hessian:
 [[ 0.00878427  0.0400167  -0.0753622   0.00386251]
 [ 0.0400167   1.06335499 -0.02634853  0.06667363]
 [-0.0753622  -0.02634853  0.99896002 -0.00552938]
 [ 0.00386251  0.06667363 -0.00552938  0.00489958]]


## b)

In [7]:
# Define the pdf function for macro series:
def pdf_macro2(wt,kt,alpha,rho,mu,sigma):
    zt = np.log(rt/(alpha*(kt**(alpha-1)))) # Finding zt using equation 4
    pdf_vals = np.empty_like(zt)
    for i in range(len(zt)):
        if i==0:
            miu = mu
        else:
            miu = rho*zt[i-1]+(1-rho)*mu
        pdf_vals[i] = (1/(sigma * np.sqrt(2 * np.pi)) *
                    np.exp( - (zt[i] - miu)**2 / (2 * sigma**2)))
    pdf_vals[pdf_vals==0] = 1e-15
    return pdf_vals

# Define log likelihood function for the Macro Series 
def log_lik_macro2(wt,kt,alpha,rho,mu,sigma):
    pdf_vals = pdf_macro2(wt,kt,alpha,rho,mu,sigma)
    ln_pdf_vals = np.log(pdf_vals)
    log_lik_val = ln_pdf_vals.sum()
    return log_lik_val

def crit2(params, *args):
    alpha,rho,mu,sigma = params
    wt,kt = args
    log_lik_val = log_lik_macro2(wt,kt,alpha,rho,mu,sigma)
    neg_log_lik_val = -log_lik_val
    return neg_log_lik_val

alpha_init = 0.5
rho_init = 0.7
mu_init = 9.5
sigma_init = 0.1
params_init = np.array([alpha_init, rho_init, mu_init, sigma_init])
args = (wt,kt)
bounds = ((1e-10,1),(-1,1),(1e-10,None),(1e-10,None))
results = opt.minimize(crit2, params_init, args=args, bounds=bounds)
alpha_MLE2, rho_MLE2, mu_MLE2, sigma_MLE2 = results.x
print(results)
print('alpha_MLE=', alpha_MLE2, 'rho_MLE=', rho_MLE2, 'mu_MLE=', mu_MLE2, 'sigma_MLE', sigma_MLE2)
print('MLE log-likelihood: ', log_lik_macro2(wt,kt,alpha_MLE2, rho_MLE2, mu_MLE2, sigma_MLE2))
print('Inverse Hessian:\n', results.hess_inv.todense())

      fun: -96.706337419869811
 hess_inv: <4x4 LbfgsInvHessProduct with dtype=float64>
      jac: array([ 0.03639542, -0.00059828,  0.01065814, -0.00317755])
  message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
     nfev: 170
      nit: 21
   status: 0
  success: True
        x: array([ 0.45016431,  0.72575966,  9.50285549,  0.09199662])
alpha_MLE= 0.450164311447 rho_MLE= 0.725759663153 mu_MLE= 9.50285548969 sigma_MLE 0.0919966218363
MLE log-likelihood:  96.7063374199
Inverse Hessian:
 [[ 0.01616501 -0.08718481 -0.05359838 -0.03881126]
 [-0.08718481  0.55776401  0.03039864  0.25162477]
 [-0.05359838  0.03039864  0.99868949 -0.00427979]
 [-0.03881126  0.25162477 -0.00427979  0.11490077]]


## c)

In [5]:
r = 1
k = 7.5e6
z_past = 10
z_star = np.log(r/(alpha_MLE*(k**(alpha_MLE-1))))
miu = rho_MLE*z_past+(1-rho_MLE)*mu_MLE
probability = 1-sts.norm.cdf(z_star,loc=miu,scale=(sigma_MLE))
print('The probability of zt > 1 is', probability)

The probability of zt > 1 is 0.999999992983
