In [126]:
import numpy as np
from scipy import linalg as la
from scipy.sparse import dok_matrix
import pandas as pd

# Problem 1

In [49]:
def problem_1(filename, N):
    #Open matrix with read
    A = dok_matrix((N,N))
    with open (filename,'r') as myfile:
        for line in myfile:
            line = line.strip().split()
            try:
                i = int(line[0])
                j = int(line[1])
                A[i,j] = 1
            except:
                continue
    return A

In [55]:
A = problem_1("/Users/rubyzhang/Desktop/UChicago/OSML/BootCamp2017/Computation/Wk4_DifIntOpt/matrix.txt",8)
print(A.toarray())

[[ 0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  0.  0.  1.  0.]
 [ 1.  0.  0.  0.  0.  1.  1.  0.]
 [ 1.  0.  0.  0.  0.  0.  1.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.]]


In [73]:
def problem_2(A):
    A = A.toarray()
    rows = np.sum(A,axis=1)
    A[rows==0,:] = 1
    D = np.sum(A,axis=1)
    K = (A.T/D)
    return K

In [74]:
print(problem_2(A))

[[ 0.          1.          0.125       0.33333333  0.33333333  0.5         1.
   1.        ]
 [ 0.          0.          0.125       0.          0.          0.          0.
   0.        ]
 [ 0.          0.          0.125       0.33333333  0.          0.          0.
   0.        ]
 [ 0.          0.          0.125       0.          0.          0.          0.
   0.        ]
 [ 0.          0.          0.125       0.          0.          0.          0.
   0.        ]
 [ 0.          0.          0.125       0.          0.33333333  0.          0.
   0.        ]
 [ 0.          0.          0.125       0.33333333  0.33333333  0.5         0.
   0.        ]
 [ 1.          0.          0.125       0.          0.          0.          0.
   0.        ]]


In [102]:
def problem_3(A, N=None, d=0.85, tol=1e-5):
    K = problem_2(A)
    A = A.toarray()
    n = A.shape[0]
    if N==None:
        N=n
    p = np.zeros(N)
    K = K[:N,:N]
    err = 1
    while err>tol:
        p_new = d*(K@p.T)+((1-d)/N)
        err = np.sqrt(np.sum((p_new-p)**2))
        p = p_new
    return p

In [103]:
print(problem_3(A))

[ 0.43865799  0.02171029  0.02786154  0.02171029  0.02171029  0.02786154
  0.04585394  0.39456563]


In [118]:
def problem_4(A,N=None,d=0.85):
    K = problem_2(A)
    A = A.toarray()
    n = A.shape[0]
    if N!=None:
        K = K[:N,:N]
    else:
        N=A.shape[0]
    B = d*K+((1-d)/N)
    eigs, vec= la.eig(B)
    return (vec[:,0]/np.sum(vec[:,0]))

In [119]:
print(problem_4(A))

[ 0.43869288  0.02171029  0.02786154  0.02171029  0.02171029  0.02786154
  0.04585394  0.39459924]


In [151]:
def problem_5(filename,d=0.7):
    data = pd.read_csv(filename,header=0,index_col=False).astype(str)
    mat_data = data.as_matrix()
    m,n = mat_data.shape
    names, inv = np.unique(mat_data, return_inverse=True)
    inv = inv.reshape((m,n))
    A = dok_matrix((len(names),len(names)))
                   
    for i in range(m):
        A[inv[i,1],inv[i,0]] = 1
    
    p = problem_3(A,d=0.7)
    sort = names[np.argsort(-p)]
    return sort

In [154]:
print(problem_5('/Users/rubyzhang/Desktop/UChicago/OSML/BootCamp2017/Computation/Wk4_DifIntOpt/ncaa2013.csv')[:5])

['Duke' 'Butler' 'Louisville' 'Illinois' 'Indiana']
